language: node_js
node_js: '10'
cache: yarn
script:
- yarn ci
deploy:
  provider: npm
  skip_cleanup: true
  email: rishabhsrao@gmail.com
  on:
    tags: true
  api_key:
    # Secure token generated and added using:
    #     $ travis encrypt --com {{raw NPM token}} --add 'deploy.api_key'
    # See https://docs.travis-ci.com/user/deployment/npm/#npm-auth-token
    secure: oQVUdAC9FFAqkpSY9Bw+j91WbGPjmLMpzS9qobfIvzvvEUgK7/u4HQ5dM4CA9aSWQ9FjI94xBkr/pEFtVSVHBLMKtLpB5YTplNvYr0CVlk4dJKE8wi3H2zlSIwUblG9NkdDCwHOtG/j7RxVXc88BoT4o7a6gFaABWWRvvAxqzyndcSMkla9FmJ2tUmg4FctsbWPLfixsFZuUOa3pRO5w0MoX6brhGlC3Ayt4SaXrEbU2on9qAUYEU054KQsJHnH+9CmQAXOcRJWTQ691QehKW5G0Trt7fyS/wpWPJxuYBRK0i1B0WuMkm6vC6YqXgvg33zPSidtRYIA2E2c7Re/lTWkSJkpomvVw4uIBTZakMqEFoOvlDPbeNboa+abudkooGBFLtuuLTwkrbUIi0RGRjG5DPCoxhvqzbKyovmdW2cjvlbI8rrNGn2lzlaRSOlTPWm6P6AQzLw2GKlRiYuXh6DzhcrUQ/Gn0oYExI6by30pZQ5z94acux+oWn/CG8zyTAW7YkUfC+VR/bzPxxthsschiwMYeOb2LJZy+IZM+nfSDQvllx9RSMW9TOxUx0188hINW720TBQhvjTDKqZ3kkGCqYS/UF506V1tc4mY/5u6MAea3aSXwNMRqgY65kwjVVzNXty2cx73sXrmL7BL7vv17uGUHRO5xHINahGerxWU=
